# Generated by Django 4.2.11 on 2024-04-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stockNumber", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("partName", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
